// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositorio.Models;

#nullable disable

namespace Repositorio.Migrations
{
    [DbContext(typeof(RepositorioContext))]
    partial class RepositorioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repositorio.Models.Coordinacion", b =>
                {
                    b.Property<int>("Id_Coordinacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Coordinacion"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id_Coordinacion");

                    b.HasIndex("Id_Usuario")
                        .IsUnique();

                    b.ToTable("Coordinaciones");
                });

            modelBuilder.Entity("Repositorio.Models.Docente", b =>
                {
                    b.Property<int>("Id_Docente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Docente"));

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id_Docente");

                    b.HasIndex("Id_Usuario")
                        .IsUnique();

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("Repositorio.Models.Estudiante", b =>
                {
                    b.Property<int>("Id_Estudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Estudiante"));

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Estudiante");

                    b.HasIndex("Id_Usuario")
                        .IsUnique();

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Repositorio.Models.Gestor", b =>
                {
                    b.Property<int>("Id_Gestor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Gestor"));

                    b.Property<string>("Area_Responsable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id_Gestor");

                    b.HasIndex("Id_Usuario")
                        .IsUnique();

                    b.ToTable("Gestores");
                });

            modelBuilder.Entity("Repositorio.Models.Metadato", b =>
                {
                    b.Property<int>("Id_Metadato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Metadato"));

                    b.Property<int>("Id_Recurso")
                        .HasColumnType("int");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Palabras_Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo_Recurso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Metadato");

                    b.HasIndex("Id_Recurso");

                    b.ToTable("Metadatos");
                });

            modelBuilder.Entity("Repositorio.Models.Metrica", b =>
                {
                    b.Property<int>("Id_Metrica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Metrica"));

                    b.Property<DateTime>("Fecha_Evento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Recurso")
                        .HasColumnType("int");

                    b.Property<string>("Tipo_Evento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Metrica");

                    b.HasIndex("Id_Recurso");

                    b.ToTable("Metricas");
                });

            modelBuilder.Entity("Repositorio.Models.Notificacion", b =>
                {
                    b.Property<int>("Id_Notificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Notificacion"));

                    b.Property<DateTime>("Fecha_Envio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_Recurso")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<bool>("Leido")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Notificacion");

                    b.HasIndex("Id_Recurso");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Repositorio.Models.Recurso", b =>
                {
                    b.Property<int>("Id_Recurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Recurso"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha_Subida")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Docente")
                        .HasColumnType("int");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Tamano")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id_Recurso");

                    b.HasIndex("Id_Docente");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("Repositorio.Models.TI", b =>
                {
                    b.Property<int>("Id_TI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_TI"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int");

                    b.HasKey("Id_TI");

                    b.HasIndex("Id_Usuario")
                        .IsUnique();

                    b.ToTable("TIs");
                });

            modelBuilder.Entity("Repositorio.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Repositorio.Models.Validacion", b =>
                {
                    b.Property<int>("Id_Validacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Validacion"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Gestor")
                        .HasColumnType("int");

                    b.Property<int>("Id_Recurso")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Validacion");

                    b.HasIndex("Id_Gestor");

                    b.HasIndex("Id_Recurso");

                    b.ToTable("Validaciones");
                });

            modelBuilder.Entity("Repositorio.Models.Version", b =>
                {
                    b.Property<int>("Id_Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Version"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Recurso")
                        .HasColumnType("int");

                    b.Property<int>("Numero_Version")
                        .HasColumnType("int");

                    b.HasKey("Id_Version");

                    b.HasIndex("Id_Recurso");

                    b.ToTable("Versiones");
                });

            modelBuilder.Entity("Repositorio.Models.Coordinacion", b =>
                {
                    b.HasOne("Repositorio.Models.Usuario", "Usuario")
                        .WithOne("Coordinacion")
                        .HasForeignKey("Repositorio.Models.Coordinacion", "Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Repositorio.Models.Docente", b =>
                {
                    b.HasOne("Repositorio.Models.Usuario", "Usuario")
                        .WithOne("Docente")
                        .HasForeignKey("Repositorio.Models.Docente", "Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Repositorio.Models.Estudiante", b =>
                {
                    b.HasOne("Repositorio.Models.Usuario", "Usuario")
                        .WithOne("Estudiante")
                        .HasForeignKey("Repositorio.Models.Estudiante", "Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Repositorio.Models.Gestor", b =>
                {
                    b.HasOne("Repositorio.Models.Usuario", "Usuario")
                        .WithOne("Gestor")
                        .HasForeignKey("Repositorio.Models.Gestor", "Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Repositorio.Models.Metadato", b =>
                {
                    b.HasOne("Repositorio.Models.Recurso", "Recurso")
                        .WithMany("Metadatos")
                        .HasForeignKey("Id_Recurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("Repositorio.Models.Metrica", b =>
                {
                    b.HasOne("Repositorio.Models.Recurso", "Recurso")
                        .WithMany("Metricas")
                        .HasForeignKey("Id_Recurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("Repositorio.Models.Notificacion", b =>
                {
                    b.HasOne("Repositorio.Models.Recurso", "Recurso")
                        .WithMany("Notificaciones")
                        .HasForeignKey("Id_Recurso");

                    b.HasOne("Repositorio.Models.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recurso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Repositorio.Models.Recurso", b =>
                {
                    b.HasOne("Repositorio.Models.Docente", "Docente")
                        .WithMany("Recursos")
                        .HasForeignKey("Id_Docente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("Repositorio.Models.TI", b =>
                {
                    b.HasOne("Repositorio.Models.Usuario", "Usuario")
                        .WithOne("TI")
                        .HasForeignKey("Repositorio.Models.TI", "Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Repositorio.Models.Validacion", b =>
                {
                    b.HasOne("Repositorio.Models.Gestor", "Gestor")
                        .WithMany("Validaciones")
                        .HasForeignKey("Id_Gestor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositorio.Models.Recurso", "Recurso")
                        .WithMany("Validaciones")
                        .HasForeignKey("Id_Recurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gestor");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("Repositorio.Models.Version", b =>
                {
                    b.HasOne("Repositorio.Models.Recurso", "Recurso")
                        .WithMany("Versiones")
                        .HasForeignKey("Id_Recurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("Repositorio.Models.Docente", b =>
                {
                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("Repositorio.Models.Gestor", b =>
                {
                    b.Navigation("Validaciones");
                });

            modelBuilder.Entity("Repositorio.Models.Recurso", b =>
                {
                    b.Navigation("Metadatos");

                    b.Navigation("Metricas");

                    b.Navigation("Notificaciones");

                    b.Navigation("Validaciones");

                    b.Navigation("Versiones");
                });

            modelBuilder.Entity("Repositorio.Models.Usuario", b =>
                {
                    b.Navigation("Coordinacion")
                        .IsRequired();

                    b.Navigation("Docente")
                        .IsRequired();

                    b.Navigation("Estudiante")
                        .IsRequired();

                    b.Navigation("Gestor")
                        .IsRequired();

                    b.Navigation("Notificaciones");

                    b.Navigation("TI")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
